root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./server cmd/api/main.go"
bin = "./server"
include_ext = ["go"]
exclude_dir = ["web", "test", "tmp", "docs", "internal/infra/httpserver/web/dist"]
delay = 100
kill_delay = "2s"
send_interrupt = true
stop_on_error = true

[log]
time = false

[misc]
clean_on_exit = true
