name: zensor-server

services:
  postgresql:
    image: postgres:14-alpine3.21
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - zensor

  redis:
    image: valkey/valkey:9.0-alpine3.22
    environment:
      ALLOW_EMPTY_PASSWORD: true
    volumes:
      - redisdata:/data
    ports:
      - "6379:6379"
    networks:
      - zensor

  prometheus:
    image: prom/prometheus:v3.7.3
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
      - --web.enable-remote-write-receiver
    networks:
      - zensor

  grafana:
    image: grafana/grafana:11.5.1
    ports:
      - "3001:3000"
    networks:
      - zensor
    depends_on:
      - prometheus

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    command: --config=/config/otelcol.yaml
    configs:
      - source: otelcol
        target: /config/otelcol.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    networks:
      - zensor

volumes:
  pgdata:
    driver: local
  redisdata:
    driver: local

networks:
  zensor:
    driver: bridge

configs:
  server:
    content: |
      general:
        log_level: info
      mqtt:
        broker: "localhost:1883"
      database:
        dsn: "host=postgresql user=postgres dbname=postgres port=5432 sslmode=disable"
      redis:
        addr: "redis:6379"
        password: ""
        db: 0
      mqtt_client:
        broker: nam1.cloud.thethings.network:1883
        client_id: zensor_server_local

  otelcol:
    content: |
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318

      processors:
        batch:
          timeout: 0ms

      exporters:
        prometheusremotewrite:
          endpoint: http://prometheus:9090/api/v1/write
          tls:
            insecure: true
        debug:
          verbosity: detailed

      service:
        pipelines:
          traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [debug]
          metrics:
            receivers: [otlp]
            processors: [batch]
            exporters: [prometheusremotewrite]
