receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:
    timeout: 0ms

exporters:
  file:
    path: ./otelcol_output.json
  debug:
    verbosity: detailed
  prometheus:
    endpoint: localhost:20000
    namespace: zensor_server
  prometheusremotewrite:
    endpoint: http://localhost:9090/api/v1/write
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [file, prometheusremotewrite]
