// Code generated by MockGen. DO NOT EDIT.
// Source: ./dose_service.go
//
// Generated by this command:
//
//	mockgen -source=./dose_service.go -destination=../../../test/unit/doubles/medicines/usecases/dose_service_mock.go -package=usecases -mock_names=DoseService=MockDoseService
//

// Package usecases is a generated GoMock package.
package usecases

import (
	context "context"
	reflect "reflect"
	time "time"
	domain "zensor-server/internal/medicines/domain"
	usecases "zensor-server/internal/medicines/usecases"
	domain0 "zensor-server/internal/shared_kernel/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockDoseService is a mock of DoseService interface.
type MockDoseService struct {
	ctrl     *gomock.Controller
	recorder *MockDoseServiceMockRecorder
	isgomock struct{}
}

// MockDoseServiceMockRecorder is the mock recorder for MockDoseService.
type MockDoseServiceMockRecorder struct {
	mock *MockDoseService
}

// NewMockDoseService creates a new mock instance.
func NewMockDoseService(ctrl *gomock.Controller) *MockDoseService {
	mock := &MockDoseService{ctrl: ctrl}
	mock.recorder = &MockDoseServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDoseService) EXPECT() *MockDoseServiceMockRecorder {
	return m.recorder
}

// AdministerDose mocks base method.
func (m *MockDoseService) AdministerDose(ctx context.Context, id domain0.ID, by domain.ResolvedBy, notes *domain.DoseNotes) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdministerDose", ctx, id, by, notes)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdministerDose indicates an expected call of AdministerDose.
func (mr *MockDoseServiceMockRecorder) AdministerDose(ctx, id, by, notes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdministerDose", reflect.TypeOf((*MockDoseService)(nil).AdministerDose), ctx, id, by, notes)
}

// GetDose mocks base method.
func (m *MockDoseService) GetDose(ctx context.Context, id domain0.ID) (domain.Dose, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDose", ctx, id)
	ret0, _ := ret[0].(domain.Dose)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDose indicates an expected call of GetDose.
func (mr *MockDoseServiceMockRecorder) GetDose(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDose", reflect.TypeOf((*MockDoseService)(nil).GetDose), ctx, id)
}

// ListAgenda mocks base method.
func (m *MockDoseService) ListAgenda(ctx context.Context, tenantID domain0.ID, from, to time.Time) ([]usecases.DoseWithContext, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAgenda", ctx, tenantID, from, to)
	ret0, _ := ret[0].([]usecases.DoseWithContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAgenda indicates an expected call of ListAgenda.
func (mr *MockDoseServiceMockRecorder) ListAgenda(ctx, tenantID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAgenda", reflect.TypeOf((*MockDoseService)(nil).ListAgenda), ctx, tenantID, from, to)
}

// ListDosesByTreatment mocks base method.
func (m *MockDoseService) ListDosesByTreatment(ctx context.Context, treatmentID domain0.ID, pagination usecases.Pagination) ([]domain.Dose, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDosesByTreatment", ctx, treatmentID, pagination)
	ret0, _ := ret[0].([]domain.Dose)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListDosesByTreatment indicates an expected call of ListDosesByTreatment.
func (mr *MockDoseServiceMockRecorder) ListDosesByTreatment(ctx, treatmentID, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDosesByTreatment", reflect.TypeOf((*MockDoseService)(nil).ListDosesByTreatment), ctx, treatmentID, pagination)
}

// SkipDose mocks base method.
func (m *MockDoseService) SkipDose(ctx context.Context, id domain0.ID, by domain.ResolvedBy, notes *domain.DoseNotes) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SkipDose", ctx, id, by, notes)
	ret0, _ := ret[0].(error)
	return ret0
}

// SkipDose indicates an expected call of SkipDose.
func (mr *MockDoseServiceMockRecorder) SkipDose(ctx, id, by, notes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SkipDose", reflect.TypeOf((*MockDoseService)(nil).SkipDose), ctx, id, by, notes)
}
