// Code generated by MockGen. DO NOT EDIT.
// Source: ./patient_service.go
//
// Generated by this command:
//
//	mockgen -source=./patient_service.go -destination=../../../test/unit/doubles/medicines/usecases/patient_service_mock.go -package=usecases -mock_names=PatientService=MockPatientService
//

// Package usecases is a generated GoMock package.
package usecases

import (
	context "context"
	reflect "reflect"
	domain "zensor-server/internal/medicines/domain"
	usecases "zensor-server/internal/medicines/usecases"
	domain0 "zensor-server/internal/shared_kernel/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockPatientService is a mock of PatientService interface.
type MockPatientService struct {
	ctrl     *gomock.Controller
	recorder *MockPatientServiceMockRecorder
	isgomock struct{}
}

// MockPatientServiceMockRecorder is the mock recorder for MockPatientService.
type MockPatientServiceMockRecorder struct {
	mock *MockPatientService
}

// NewMockPatientService creates a new mock instance.
func NewMockPatientService(ctrl *gomock.Controller) *MockPatientService {
	mock := &MockPatientService{ctrl: ctrl}
	mock.recorder = &MockPatientServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPatientService) EXPECT() *MockPatientServiceMockRecorder {
	return m.recorder
}

// CreatePatient mocks base method.
func (m *MockPatientService) CreatePatient(ctx context.Context, patient domain.Patient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePatient", ctx, patient)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePatient indicates an expected call of CreatePatient.
func (mr *MockPatientServiceMockRecorder) CreatePatient(ctx, patient any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePatient", reflect.TypeOf((*MockPatientService)(nil).CreatePatient), ctx, patient)
}

// DeletePatient mocks base method.
func (m *MockPatientService) DeletePatient(ctx context.Context, id domain0.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePatient", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePatient indicates an expected call of DeletePatient.
func (mr *MockPatientServiceMockRecorder) DeletePatient(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePatient", reflect.TypeOf((*MockPatientService)(nil).DeletePatient), ctx, id)
}

// GetPatient mocks base method.
func (m *MockPatientService) GetPatient(ctx context.Context, id domain0.ID) (domain.Patient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPatient", ctx, id)
	ret0, _ := ret[0].(domain.Patient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPatient indicates an expected call of GetPatient.
func (mr *MockPatientServiceMockRecorder) GetPatient(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPatient", reflect.TypeOf((*MockPatientService)(nil).GetPatient), ctx, id)
}

// ListPatientsByTenant mocks base method.
func (m *MockPatientService) ListPatientsByTenant(ctx context.Context, tenantID domain0.ID, pagination usecases.Pagination) ([]domain.Patient, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPatientsByTenant", ctx, tenantID, pagination)
	ret0, _ := ret[0].([]domain.Patient)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListPatientsByTenant indicates an expected call of ListPatientsByTenant.
func (mr *MockPatientServiceMockRecorder) ListPatientsByTenant(ctx, tenantID, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPatientsByTenant", reflect.TypeOf((*MockPatientService)(nil).ListPatientsByTenant), ctx, tenantID, pagination)
}

// UpdatePatient mocks base method.
func (m *MockPatientService) UpdatePatient(ctx context.Context, patient domain.Patient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePatient", ctx, patient)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePatient indicates an expected call of UpdatePatient.
func (mr *MockPatientServiceMockRecorder) UpdatePatient(ctx, patient any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePatient", reflect.TypeOf((*MockPatientService)(nil).UpdatePatient), ctx, patient)
}
