// Code generated by MockGen. DO NOT EDIT.
// Source: repository_port.go
//
// Generated by this command:
//
//	mockgen -source=repository_port.go -destination=../../../test/unit/doubles/medicines/usecases/repository_port_mock.go -package=usecases -mock_names=PatientRepository=MockPatientRepository,TreatmentRepository=MockTreatmentRepository,DoseRepository=MockDoseRepository
//

// Package usecases is a generated GoMock package.
package usecases

import (
	context "context"
	reflect "reflect"
	time "time"
	domain "zensor-server/internal/medicines/domain"
	usecases "zensor-server/internal/medicines/usecases"
	domain0 "zensor-server/internal/shared_kernel/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockPatientRepository is a mock of PatientRepository interface.
type MockPatientRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPatientRepositoryMockRecorder
	isgomock struct{}
}

// MockPatientRepositoryMockRecorder is the mock recorder for MockPatientRepository.
type MockPatientRepositoryMockRecorder struct {
	mock *MockPatientRepository
}

// NewMockPatientRepository creates a new mock instance.
func NewMockPatientRepository(ctrl *gomock.Controller) *MockPatientRepository {
	mock := &MockPatientRepository{ctrl: ctrl}
	mock.recorder = &MockPatientRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPatientRepository) EXPECT() *MockPatientRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPatientRepository) Create(ctx context.Context, patient domain.Patient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, patient)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPatientRepositoryMockRecorder) Create(ctx, patient any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPatientRepository)(nil).Create), ctx, patient)
}

// Delete mocks base method.
func (m *MockPatientRepository) Delete(ctx context.Context, id domain0.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPatientRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPatientRepository)(nil).Delete), ctx, id)
}

// FindAllByTenant mocks base method.
func (m *MockPatientRepository) FindAllByTenant(ctx context.Context, tenantID domain0.ID, pagination usecases.Pagination) ([]domain.Patient, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByTenant", ctx, tenantID, pagination)
	ret0, _ := ret[0].([]domain.Patient)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAllByTenant indicates an expected call of FindAllByTenant.
func (mr *MockPatientRepositoryMockRecorder) FindAllByTenant(ctx, tenantID, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByTenant", reflect.TypeOf((*MockPatientRepository)(nil).FindAllByTenant), ctx, tenantID, pagination)
}

// GetByID mocks base method.
func (m *MockPatientRepository) GetByID(ctx context.Context, id domain0.ID) (domain.Patient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.Patient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPatientRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPatientRepository)(nil).GetByID), ctx, id)
}

// Update mocks base method.
func (m *MockPatientRepository) Update(ctx context.Context, patient domain.Patient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, patient)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPatientRepositoryMockRecorder) Update(ctx, patient any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPatientRepository)(nil).Update), ctx, patient)
}

// MockTreatmentRepository is a mock of TreatmentRepository interface.
type MockTreatmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTreatmentRepositoryMockRecorder
	isgomock struct{}
}

// MockTreatmentRepositoryMockRecorder is the mock recorder for MockTreatmentRepository.
type MockTreatmentRepositoryMockRecorder struct {
	mock *MockTreatmentRepository
}

// NewMockTreatmentRepository creates a new mock instance.
func NewMockTreatmentRepository(ctrl *gomock.Controller) *MockTreatmentRepository {
	mock := &MockTreatmentRepository{ctrl: ctrl}
	mock.recorder = &MockTreatmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTreatmentRepository) EXPECT() *MockTreatmentRepositoryMockRecorder {
	return m.recorder
}

// CountActiveByPatient mocks base method.
func (m *MockTreatmentRepository) CountActiveByPatient(ctx context.Context, patientID domain0.ID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveByPatient", ctx, patientID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveByPatient indicates an expected call of CountActiveByPatient.
func (mr *MockTreatmentRepositoryMockRecorder) CountActiveByPatient(ctx, patientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveByPatient", reflect.TypeOf((*MockTreatmentRepository)(nil).CountActiveByPatient), ctx, patientID)
}

// Create mocks base method.
func (m *MockTreatmentRepository) Create(ctx context.Context, treatment domain.Treatment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, treatment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTreatmentRepositoryMockRecorder) Create(ctx, treatment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTreatmentRepository)(nil).Create), ctx, treatment)
}

// Delete mocks base method.
func (m *MockTreatmentRepository) Delete(ctx context.Context, id domain0.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTreatmentRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTreatmentRepository)(nil).Delete), ctx, id)
}

// FindAllActive mocks base method.
func (m *MockTreatmentRepository) FindAllActive(ctx context.Context) ([]domain.Treatment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllActive", ctx)
	ret0, _ := ret[0].([]domain.Treatment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllActive indicates an expected call of FindAllActive.
func (mr *MockTreatmentRepositoryMockRecorder) FindAllActive(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllActive", reflect.TypeOf((*MockTreatmentRepository)(nil).FindAllActive), ctx)
}

// FindAllByPatient mocks base method.
func (m *MockTreatmentRepository) FindAllByPatient(ctx context.Context, patientID domain0.ID, pagination usecases.Pagination) ([]domain.Treatment, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByPatient", ctx, patientID, pagination)
	ret0, _ := ret[0].([]domain.Treatment)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAllByPatient indicates an expected call of FindAllByPatient.
func (mr *MockTreatmentRepositoryMockRecorder) FindAllByPatient(ctx, patientID, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByPatient", reflect.TypeOf((*MockTreatmentRepository)(nil).FindAllByPatient), ctx, patientID, pagination)
}

// FindAllByTenant mocks base method.
func (m *MockTreatmentRepository) FindAllByTenant(ctx context.Context, tenantID domain0.ID, pagination usecases.Pagination) ([]domain.Treatment, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByTenant", ctx, tenantID, pagination)
	ret0, _ := ret[0].([]domain.Treatment)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAllByTenant indicates an expected call of FindAllByTenant.
func (mr *MockTreatmentRepositoryMockRecorder) FindAllByTenant(ctx, tenantID, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByTenant", reflect.TypeOf((*MockTreatmentRepository)(nil).FindAllByTenant), ctx, tenantID, pagination)
}

// GetByID mocks base method.
func (m *MockTreatmentRepository) GetByID(ctx context.Context, id domain0.ID) (domain.Treatment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.Treatment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTreatmentRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTreatmentRepository)(nil).GetByID), ctx, id)
}

// Update mocks base method.
func (m *MockTreatmentRepository) Update(ctx context.Context, treatment domain.Treatment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, treatment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTreatmentRepositoryMockRecorder) Update(ctx, treatment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTreatmentRepository)(nil).Update), ctx, treatment)
}

// MockDoseRepository is a mock of DoseRepository interface.
type MockDoseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDoseRepositoryMockRecorder
	isgomock struct{}
}

// MockDoseRepositoryMockRecorder is the mock recorder for MockDoseRepository.
type MockDoseRepositoryMockRecorder struct {
	mock *MockDoseRepository
}

// NewMockDoseRepository creates a new mock instance.
func NewMockDoseRepository(ctrl *gomock.Controller) *MockDoseRepository {
	mock := &MockDoseRepository{ctrl: ctrl}
	mock.recorder = &MockDoseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDoseRepository) EXPECT() *MockDoseRepositoryMockRecorder {
	return m.recorder
}

// CreateBatch mocks base method.
func (m *MockDoseRepository) CreateBatch(ctx context.Context, doses []domain.Dose) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", ctx, doses)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockDoseRepositoryMockRecorder) CreateBatch(ctx, doses any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockDoseRepository)(nil).CreateBatch), ctx, doses)
}

// DeletePendingFrom mocks base method.
func (m *MockDoseRepository) DeletePendingFrom(ctx context.Context, treatmentID domain0.ID, from time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePendingFrom", ctx, treatmentID, from)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePendingFrom indicates an expected call of DeletePendingFrom.
func (mr *MockDoseRepositoryMockRecorder) DeletePendingFrom(ctx, treatmentID, from any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePendingFrom", reflect.TypeOf((*MockDoseRepository)(nil).DeletePendingFrom), ctx, treatmentID, from)
}

// FindAgenda mocks base method.
func (m *MockDoseRepository) FindAgenda(ctx context.Context, tenantID domain0.ID, from, to time.Time, limit int) ([]usecases.DoseWithContext, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAgenda", ctx, tenantID, from, to, limit)
	ret0, _ := ret[0].([]usecases.DoseWithContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAgenda indicates an expected call of FindAgenda.
func (mr *MockDoseRepositoryMockRecorder) FindAgenda(ctx, tenantID, from, to, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAgenda", reflect.TypeOf((*MockDoseRepository)(nil).FindAgenda), ctx, tenantID, from, to, limit)
}

// FindAllByTreatment mocks base method.
func (m *MockDoseRepository) FindAllByTreatment(ctx context.Context, treatmentID domain0.ID, pagination usecases.Pagination) ([]domain.Dose, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByTreatment", ctx, treatmentID, pagination)
	ret0, _ := ret[0].([]domain.Dose)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAllByTreatment indicates an expected call of FindAllByTreatment.
func (mr *MockDoseRepositoryMockRecorder) FindAllByTreatment(ctx, treatmentID, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByTreatment", reflect.TypeOf((*MockDoseRepository)(nil).FindAllByTreatment), ctx, treatmentID, pagination)
}

// FindByTreatmentInWindow mocks base method.
func (m *MockDoseRepository) FindByTreatmentInWindow(ctx context.Context, treatmentID domain0.ID, from, to time.Time) ([]domain.Dose, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTreatmentInWindow", ctx, treatmentID, from, to)
	ret0, _ := ret[0].([]domain.Dose)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTreatmentInWindow indicates an expected call of FindByTreatmentInWindow.
func (mr *MockDoseRepositoryMockRecorder) FindByTreatmentInWindow(ctx, treatmentID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTreatmentInWindow", reflect.TypeOf((*MockDoseRepository)(nil).FindByTreatmentInWindow), ctx, treatmentID, from, to)
}

// FindDueForReminder mocks base method.
func (m *MockDoseRepository) FindDueForReminder(ctx context.Context, from, to time.Time, limit int) ([]usecases.DoseWithContext, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDueForReminder", ctx, from, to, limit)
	ret0, _ := ret[0].([]usecases.DoseWithContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDueForReminder indicates an expected call of FindDueForReminder.
func (mr *MockDoseRepositoryMockRecorder) FindDueForReminder(ctx, from, to, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDueForReminder", reflect.TypeOf((*MockDoseRepository)(nil).FindDueForReminder), ctx, from, to, limit)
}

// GetByID mocks base method.
func (m *MockDoseRepository) GetByID(ctx context.Context, id domain0.ID) (domain.Dose, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.Dose)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDoseRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDoseRepository)(nil).GetByID), ctx, id)
}

// Update mocks base method.
func (m *MockDoseRepository) Update(ctx context.Context, dose domain.Dose) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, dose)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDoseRepositoryMockRecorder) Update(ctx, dose any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDoseRepository)(nil).Update), ctx, dose)
}
