// Code generated by MockGen. DO NOT EDIT.
// Source: ./treatment_service.go
//
// Generated by this command:
//
//	mockgen -source=./treatment_service.go -destination=../../../test/unit/doubles/medicines/usecases/treatment_service_mock.go -package=usecases -mock_names=TreatmentService=MockTreatmentService
//

// Package usecases is a generated GoMock package.
package usecases

import (
	context "context"
	reflect "reflect"
	domain "zensor-server/internal/medicines/domain"
	usecases "zensor-server/internal/medicines/usecases"
	domain0 "zensor-server/internal/shared_kernel/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockTreatmentService is a mock of TreatmentService interface.
type MockTreatmentService struct {
	ctrl     *gomock.Controller
	recorder *MockTreatmentServiceMockRecorder
	isgomock struct{}
}

// MockTreatmentServiceMockRecorder is the mock recorder for MockTreatmentService.
type MockTreatmentServiceMockRecorder struct {
	mock *MockTreatmentService
}

// NewMockTreatmentService creates a new mock instance.
func NewMockTreatmentService(ctrl *gomock.Controller) *MockTreatmentService {
	mock := &MockTreatmentService{ctrl: ctrl}
	mock.recorder = &MockTreatmentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTreatmentService) EXPECT() *MockTreatmentServiceMockRecorder {
	return m.recorder
}

// ActivateTreatment mocks base method.
func (m *MockTreatmentService) ActivateTreatment(ctx context.Context, id domain0.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateTreatment", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateTreatment indicates an expected call of ActivateTreatment.
func (mr *MockTreatmentServiceMockRecorder) ActivateTreatment(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateTreatment", reflect.TypeOf((*MockTreatmentService)(nil).ActivateTreatment), ctx, id)
}

// CreateTreatment mocks base method.
func (m *MockTreatmentService) CreateTreatment(ctx context.Context, treatment domain.Treatment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTreatment", ctx, treatment)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTreatment indicates an expected call of CreateTreatment.
func (mr *MockTreatmentServiceMockRecorder) CreateTreatment(ctx, treatment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTreatment", reflect.TypeOf((*MockTreatmentService)(nil).CreateTreatment), ctx, treatment)
}

// DeactivateTreatment mocks base method.
func (m *MockTreatmentService) DeactivateTreatment(ctx context.Context, id domain0.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateTreatment", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateTreatment indicates an expected call of DeactivateTreatment.
func (mr *MockTreatmentServiceMockRecorder) DeactivateTreatment(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateTreatment", reflect.TypeOf((*MockTreatmentService)(nil).DeactivateTreatment), ctx, id)
}

// DeleteTreatment mocks base method.
func (m *MockTreatmentService) DeleteTreatment(ctx context.Context, id domain0.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTreatment", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTreatment indicates an expected call of DeleteTreatment.
func (mr *MockTreatmentServiceMockRecorder) DeleteTreatment(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTreatment", reflect.TypeOf((*MockTreatmentService)(nil).DeleteTreatment), ctx, id)
}

// GetTreatment mocks base method.
func (m *MockTreatmentService) GetTreatment(ctx context.Context, id domain0.ID) (domain.Treatment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTreatment", ctx, id)
	ret0, _ := ret[0].(domain.Treatment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTreatment indicates an expected call of GetTreatment.
func (mr *MockTreatmentServiceMockRecorder) GetTreatment(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTreatment", reflect.TypeOf((*MockTreatmentService)(nil).GetTreatment), ctx, id)
}

// ListTreatmentsByPatient mocks base method.
func (m *MockTreatmentService) ListTreatmentsByPatient(ctx context.Context, patientID domain0.ID, pagination usecases.Pagination) ([]domain.Treatment, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTreatmentsByPatient", ctx, patientID, pagination)
	ret0, _ := ret[0].([]domain.Treatment)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTreatmentsByPatient indicates an expected call of ListTreatmentsByPatient.
func (mr *MockTreatmentServiceMockRecorder) ListTreatmentsByPatient(ctx, patientID, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTreatmentsByPatient", reflect.TypeOf((*MockTreatmentService)(nil).ListTreatmentsByPatient), ctx, patientID, pagination)
}

// ListTreatmentsByTenant mocks base method.
func (m *MockTreatmentService) ListTreatmentsByTenant(ctx context.Context, tenantID domain0.ID, pagination usecases.Pagination) ([]domain.Treatment, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTreatmentsByTenant", ctx, tenantID, pagination)
	ret0, _ := ret[0].([]domain.Treatment)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTreatmentsByTenant indicates an expected call of ListTreatmentsByTenant.
func (mr *MockTreatmentServiceMockRecorder) ListTreatmentsByTenant(ctx, tenantID, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTreatmentsByTenant", reflect.TypeOf((*MockTreatmentService)(nil).ListTreatmentsByTenant), ctx, tenantID, pagination)
}

// UpdateTreatment mocks base method.
func (m *MockTreatmentService) UpdateTreatment(ctx context.Context, treatment domain.Treatment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTreatment", ctx, treatment)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTreatment indicates an expected call of UpdateTreatment.
func (mr *MockTreatmentServiceMockRecorder) UpdateTreatment(ctx, treatment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTreatment", reflect.TypeOf((*MockTreatmentService)(nil).UpdateTreatment), ctx, treatment)
}
