// Code generated by MockGen. DO NOT EDIT.
// Source: maintenance_activity_service.go
//
// Generated by this command:
//
//	mockgen -source=maintenance_activity_service.go -destination=../../../test/unit/doubles/maintenance/usecases/maintenance_activity_service_mock.go -package=usecases -mock_names=ActivityService=MockActivityService
//

// Package usecases is a generated GoMock package.
package usecases

import (
	context "context"
	reflect "reflect"
	domain "zensor-server/internal/maintenance/domain"
	usecases "zensor-server/internal/maintenance/usecases"
	domain0 "zensor-server/internal/shared_kernel/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockActivityService is a mock of ActivityService interface.
type MockActivityService struct {
	ctrl     *gomock.Controller
	recorder *MockActivityServiceMockRecorder
	isgomock struct{}
}

// MockActivityServiceMockRecorder is the mock recorder for MockActivityService.
type MockActivityServiceMockRecorder struct {
	mock *MockActivityService
}

// NewMockActivityService creates a new mock instance.
func NewMockActivityService(ctrl *gomock.Controller) *MockActivityService {
	mock := &MockActivityService{ctrl: ctrl}
	mock.recorder = &MockActivityServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActivityService) EXPECT() *MockActivityServiceMockRecorder {
	return m.recorder
}

// ActivateActivity mocks base method.
func (m *MockActivityService) ActivateActivity(ctx context.Context, id domain0.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateActivity", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateActivity indicates an expected call of ActivateActivity.
func (mr *MockActivityServiceMockRecorder) ActivateActivity(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateActivity", reflect.TypeOf((*MockActivityService)(nil).ActivateActivity), ctx, id)
}

// CreateActivity mocks base method.
func (m *MockActivityService) CreateActivity(ctx context.Context, activity domain.Activity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateActivity", ctx, activity)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateActivity indicates an expected call of CreateActivity.
func (mr *MockActivityServiceMockRecorder) CreateActivity(ctx, activity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateActivity", reflect.TypeOf((*MockActivityService)(nil).CreateActivity), ctx, activity)
}

// DeactivateActivity mocks base method.
func (m *MockActivityService) DeactivateActivity(ctx context.Context, id domain0.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateActivity", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateActivity indicates an expected call of DeactivateActivity.
func (mr *MockActivityServiceMockRecorder) DeactivateActivity(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateActivity", reflect.TypeOf((*MockActivityService)(nil).DeactivateActivity), ctx, id)
}

// DeleteActivity mocks base method.
func (m *MockActivityService) DeleteActivity(ctx context.Context, id domain0.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteActivity", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteActivity indicates an expected call of DeleteActivity.
func (mr *MockActivityServiceMockRecorder) DeleteActivity(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteActivity", reflect.TypeOf((*MockActivityService)(nil).DeleteActivity), ctx, id)
}

// GetActivity mocks base method.
func (m *MockActivityService) GetActivity(ctx context.Context, id domain0.ID) (domain.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivity", ctx, id)
	ret0, _ := ret[0].(domain.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActivity indicates an expected call of GetActivity.
func (mr *MockActivityServiceMockRecorder) GetActivity(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivity", reflect.TypeOf((*MockActivityService)(nil).GetActivity), ctx, id)
}

// ListActivitiesByTenant mocks base method.
func (m *MockActivityService) ListActivitiesByTenant(ctx context.Context, tenantID domain0.ID, pagination usecases.Pagination) ([]domain.Activity, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActivitiesByTenant", ctx, tenantID, pagination)
	ret0, _ := ret[0].([]domain.Activity)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListActivitiesByTenant indicates an expected call of ListActivitiesByTenant.
func (mr *MockActivityServiceMockRecorder) ListActivitiesByTenant(ctx, tenantID, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActivitiesByTenant", reflect.TypeOf((*MockActivityService)(nil).ListActivitiesByTenant), ctx, tenantID, pagination)
}

// UpdateActivity mocks base method.
func (m *MockActivityService) UpdateActivity(ctx context.Context, activity domain.Activity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateActivity", ctx, activity)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateActivity indicates an expected call of UpdateActivity.
func (mr *MockActivityServiceMockRecorder) UpdateActivity(ctx, activity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateActivity", reflect.TypeOf((*MockActivityService)(nil).UpdateActivity), ctx, activity)
}
