// Code generated by MockGen. DO NOT EDIT.
// Source: maintenance_activity_service.go
//
// Generated by this command:
//
//	mockgen -source=maintenance_activity_service.go -destination=../../../test/unit/doubles/maintenance/usecases/maintenance_activity_service_mock.go -package=usecases -mock_names=MaintenanceActivityService=MockMaintenanceActivityService
//

// Package usecases is a generated GoMock package.
package usecases

import (
	context "context"
	reflect "reflect"
	domain "zensor-server/internal/maintenance/domain"
	usecases "zensor-server/internal/maintenance/usecases"
	domain0 "zensor-server/internal/shared_kernel/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockMaintenanceActivityService is a mock of MaintenanceActivityService interface.
type MockMaintenanceActivityService struct {
	ctrl     *gomock.Controller
	recorder *MockMaintenanceActivityServiceMockRecorder
	isgomock struct{}
}

// MockMaintenanceActivityServiceMockRecorder is the mock recorder for MockMaintenanceActivityService.
type MockMaintenanceActivityServiceMockRecorder struct {
	mock *MockMaintenanceActivityService
}

// NewMockMaintenanceActivityService creates a new mock instance.
func NewMockMaintenanceActivityService(ctrl *gomock.Controller) *MockMaintenanceActivityService {
	mock := &MockMaintenanceActivityService{ctrl: ctrl}
	mock.recorder = &MockMaintenanceActivityServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMaintenanceActivityService) EXPECT() *MockMaintenanceActivityServiceMockRecorder {
	return m.recorder
}

// ActivateActivity mocks base method.
func (m *MockMaintenanceActivityService) ActivateActivity(ctx context.Context, id domain0.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateActivity", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateActivity indicates an expected call of ActivateActivity.
func (mr *MockMaintenanceActivityServiceMockRecorder) ActivateActivity(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateActivity", reflect.TypeOf((*MockMaintenanceActivityService)(nil).ActivateActivity), ctx, id)
}

// CreateActivity mocks base method.
func (m *MockMaintenanceActivityService) CreateActivity(ctx context.Context, activity domain.MaintenanceActivity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateActivity", ctx, activity)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateActivity indicates an expected call of CreateActivity.
func (mr *MockMaintenanceActivityServiceMockRecorder) CreateActivity(ctx, activity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateActivity", reflect.TypeOf((*MockMaintenanceActivityService)(nil).CreateActivity), ctx, activity)
}

// DeactivateActivity mocks base method.
func (m *MockMaintenanceActivityService) DeactivateActivity(ctx context.Context, id domain0.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateActivity", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateActivity indicates an expected call of DeactivateActivity.
func (mr *MockMaintenanceActivityServiceMockRecorder) DeactivateActivity(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateActivity", reflect.TypeOf((*MockMaintenanceActivityService)(nil).DeactivateActivity), ctx, id)
}

// DeleteActivity mocks base method.
func (m *MockMaintenanceActivityService) DeleteActivity(ctx context.Context, id domain0.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteActivity", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteActivity indicates an expected call of DeleteActivity.
func (mr *MockMaintenanceActivityServiceMockRecorder) DeleteActivity(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteActivity", reflect.TypeOf((*MockMaintenanceActivityService)(nil).DeleteActivity), ctx, id)
}

// GetActivity mocks base method.
func (m *MockMaintenanceActivityService) GetActivity(ctx context.Context, id domain0.ID) (domain.MaintenanceActivity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivity", ctx, id)
	ret0, _ := ret[0].(domain.MaintenanceActivity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActivity indicates an expected call of GetActivity.
func (mr *MockMaintenanceActivityServiceMockRecorder) GetActivity(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivity", reflect.TypeOf((*MockMaintenanceActivityService)(nil).GetActivity), ctx, id)
}

// ListActivitiesByTenant mocks base method.
func (m *MockMaintenanceActivityService) ListActivitiesByTenant(ctx context.Context, tenantID domain0.ID, pagination usecases.Pagination) ([]domain.MaintenanceActivity, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActivitiesByTenant", ctx, tenantID, pagination)
	ret0, _ := ret[0].([]domain.MaintenanceActivity)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListActivitiesByTenant indicates an expected call of ListActivitiesByTenant.
func (mr *MockMaintenanceActivityServiceMockRecorder) ListActivitiesByTenant(ctx, tenantID, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActivitiesByTenant", reflect.TypeOf((*MockMaintenanceActivityService)(nil).ListActivitiesByTenant), ctx, tenantID, pagination)
}

// UpdateActivity mocks base method.
func (m *MockMaintenanceActivityService) UpdateActivity(ctx context.Context, activity domain.MaintenanceActivity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateActivity", ctx, activity)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateActivity indicates an expected call of UpdateActivity.
func (mr *MockMaintenanceActivityServiceMockRecorder) UpdateActivity(ctx, activity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateActivity", reflect.TypeOf((*MockMaintenanceActivityService)(nil).UpdateActivity), ctx, activity)
}
