// Code generated by MockGen. DO NOT EDIT.
// Source: maintenance_execution_service.go
//
// Generated by this command:
//
//	mockgen -source=maintenance_execution_service.go -destination=../../../test/unit/doubles/maintenance/usecases/maintenance_execution_service_mock.go -package=usecases -mock_names=ExecutionService=MockExecutionService
//

// Package usecases is a generated GoMock package.
package usecases

import (
	context "context"
	reflect "reflect"
	domain "zensor-server/internal/maintenance/domain"
	usecases "zensor-server/internal/maintenance/usecases"
	domain0 "zensor-server/internal/shared_kernel/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockExecutionService is a mock of ExecutionService interface.
type MockExecutionService struct {
	ctrl     *gomock.Controller
	recorder *MockExecutionServiceMockRecorder
	isgomock struct{}
}

// MockExecutionServiceMockRecorder is the mock recorder for MockExecutionService.
type MockExecutionServiceMockRecorder struct {
	mock *MockExecutionService
}

// NewMockExecutionService creates a new mock instance.
func NewMockExecutionService(ctrl *gomock.Controller) *MockExecutionService {
	mock := &MockExecutionService{ctrl: ctrl}
	mock.recorder = &MockExecutionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutionService) EXPECT() *MockExecutionServiceMockRecorder {
	return m.recorder
}

// CreateExecution mocks base method.
func (m *MockExecutionService) CreateExecution(ctx context.Context, execution domain.Execution) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateExecution", ctx, execution)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateExecution indicates an expected call of CreateExecution.
func (mr *MockExecutionServiceMockRecorder) CreateExecution(ctx, execution any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExecution", reflect.TypeOf((*MockExecutionService)(nil).CreateExecution), ctx, execution)
}

// GetExecution mocks base method.
func (m *MockExecutionService) GetExecution(ctx context.Context, id domain0.ID) (domain.Execution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExecution", ctx, id)
	ret0, _ := ret[0].(domain.Execution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExecution indicates an expected call of GetExecution.
func (mr *MockExecutionServiceMockRecorder) GetExecution(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExecution", reflect.TypeOf((*MockExecutionService)(nil).GetExecution), ctx, id)
}

// ListExecutionsByActivity mocks base method.
func (m *MockExecutionService) ListExecutionsByActivity(ctx context.Context, activityID domain0.ID, pagination usecases.Pagination) ([]domain.Execution, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExecutionsByActivity", ctx, activityID, pagination)
	ret0, _ := ret[0].([]domain.Execution)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListExecutionsByActivity indicates an expected call of ListExecutionsByActivity.
func (mr *MockExecutionServiceMockRecorder) ListExecutionsByActivity(ctx, activityID, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExecutionsByActivity", reflect.TypeOf((*MockExecutionService)(nil).ListExecutionsByActivity), ctx, activityID, pagination)
}

// MarkExecutionCompleted mocks base method.
func (m *MockExecutionService) MarkExecutionCompleted(ctx context.Context, id domain0.ID, completedBy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkExecutionCompleted", ctx, id, completedBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkExecutionCompleted indicates an expected call of MarkExecutionCompleted.
func (mr *MockExecutionServiceMockRecorder) MarkExecutionCompleted(ctx, id, completedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkExecutionCompleted", reflect.TypeOf((*MockExecutionService)(nil).MarkExecutionCompleted), ctx, id, completedBy)
}
