// Code generated by MockGen. DO NOT EDIT.
// Source: repository_port.go
//
// Generated by this command:
//
//	mockgen -source=repository_port.go -destination=../../../test/unit/doubles/maintenance/usecases/repository_port_mock.go -package=usecases -mock_names=ActivityRepository=MockActivityRepository,ExecutionRepository=MockExecutionRepository
//

// Package usecases is a generated GoMock package.
package usecases

import (
	context "context"
	reflect "reflect"
	time "time"
	domain "zensor-server/internal/maintenance/domain"
	usecases "zensor-server/internal/maintenance/usecases"
	domain0 "zensor-server/internal/shared_kernel/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockActivityRepository is a mock of ActivityRepository interface.
type MockActivityRepository struct {
	ctrl     *gomock.Controller
	recorder *MockActivityRepositoryMockRecorder
	isgomock struct{}
}

// MockActivityRepositoryMockRecorder is the mock recorder for MockActivityRepository.
type MockActivityRepositoryMockRecorder struct {
	mock *MockActivityRepository
}

// NewMockActivityRepository creates a new mock instance.
func NewMockActivityRepository(ctrl *gomock.Controller) *MockActivityRepository {
	mock := &MockActivityRepository{ctrl: ctrl}
	mock.recorder = &MockActivityRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActivityRepository) EXPECT() *MockActivityRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockActivityRepository) Create(ctx context.Context, activity domain.Activity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, activity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockActivityRepositoryMockRecorder) Create(ctx, activity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockActivityRepository)(nil).Create), ctx, activity)
}

// Delete mocks base method.
func (m *MockActivityRepository) Delete(ctx context.Context, id domain0.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockActivityRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockActivityRepository)(nil).Delete), ctx, id)
}

// FindAllActive mocks base method.
func (m *MockActivityRepository) FindAllActive(ctx context.Context) ([]domain.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllActive", ctx)
	ret0, _ := ret[0].([]domain.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllActive indicates an expected call of FindAllActive.
func (mr *MockActivityRepositoryMockRecorder) FindAllActive(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllActive", reflect.TypeOf((*MockActivityRepository)(nil).FindAllActive), ctx)
}

// FindAllByTenant mocks base method.
func (m *MockActivityRepository) FindAllByTenant(ctx context.Context, tenantID domain0.ID, pagination usecases.Pagination) ([]domain.Activity, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByTenant", ctx, tenantID, pagination)
	ret0, _ := ret[0].([]domain.Activity)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAllByTenant indicates an expected call of FindAllByTenant.
func (mr *MockActivityRepositoryMockRecorder) FindAllByTenant(ctx, tenantID, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByTenant", reflect.TypeOf((*MockActivityRepository)(nil).FindAllByTenant), ctx, tenantID, pagination)
}

// GetByID mocks base method.
func (m *MockActivityRepository) GetByID(ctx context.Context, id domain0.ID) (domain.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockActivityRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockActivityRepository)(nil).GetByID), ctx, id)
}

// Update mocks base method.
func (m *MockActivityRepository) Update(ctx context.Context, activity domain.Activity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, activity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockActivityRepositoryMockRecorder) Update(ctx, activity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockActivityRepository)(nil).Update), ctx, activity)
}

// MockExecutionRepository is a mock of ExecutionRepository interface.
type MockExecutionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockExecutionRepositoryMockRecorder
	isgomock struct{}
}

// MockExecutionRepositoryMockRecorder is the mock recorder for MockExecutionRepository.
type MockExecutionRepositoryMockRecorder struct {
	mock *MockExecutionRepository
}

// NewMockExecutionRepository creates a new mock instance.
func NewMockExecutionRepository(ctrl *gomock.Controller) *MockExecutionRepository {
	mock := &MockExecutionRepository{ctrl: ctrl}
	mock.recorder = &MockExecutionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutionRepository) EXPECT() *MockExecutionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockExecutionRepository) Create(ctx context.Context, execution domain.Execution) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, execution)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockExecutionRepositoryMockRecorder) Create(ctx, execution any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockExecutionRepository)(nil).Create), ctx, execution)
}

// FindAllByActivity mocks base method.
func (m *MockExecutionRepository) FindAllByActivity(ctx context.Context, activityID domain0.ID, pagination usecases.Pagination) ([]domain.Execution, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByActivity", ctx, activityID, pagination)
	ret0, _ := ret[0].([]domain.Execution)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAllByActivity indicates an expected call of FindAllByActivity.
func (mr *MockExecutionRepositoryMockRecorder) FindAllByActivity(ctx, activityID, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByActivity", reflect.TypeOf((*MockExecutionRepository)(nil).FindAllByActivity), ctx, activityID, pagination)
}

// FindAllDueSoon mocks base method.
func (m *MockExecutionRepository) FindAllDueSoon(ctx context.Context, tenantID domain0.ID, days int) ([]domain.Execution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllDueSoon", ctx, tenantID, days)
	ret0, _ := ret[0].([]domain.Execution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllDueSoon indicates an expected call of FindAllDueSoon.
func (mr *MockExecutionRepositoryMockRecorder) FindAllDueSoon(ctx, tenantID, days any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllDueSoon", reflect.TypeOf((*MockExecutionRepository)(nil).FindAllDueSoon), ctx, tenantID, days)
}

// FindAllOverdue mocks base method.
func (m *MockExecutionRepository) FindAllOverdue(ctx context.Context, tenantID domain0.ID) ([]domain.Execution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllOverdue", ctx, tenantID)
	ret0, _ := ret[0].([]domain.Execution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllOverdue indicates an expected call of FindAllOverdue.
func (mr *MockExecutionRepositoryMockRecorder) FindAllOverdue(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllOverdue", reflect.TypeOf((*MockExecutionRepository)(nil).FindAllOverdue), ctx, tenantID)
}

// FindByActivityAndScheduledDate mocks base method.
func (m *MockExecutionRepository) FindByActivityAndScheduledDate(ctx context.Context, activityID domain0.ID, scheduledDate time.Time) (domain.Execution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByActivityAndScheduledDate", ctx, activityID, scheduledDate)
	ret0, _ := ret[0].(domain.Execution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByActivityAndScheduledDate indicates an expected call of FindByActivityAndScheduledDate.
func (mr *MockExecutionRepositoryMockRecorder) FindByActivityAndScheduledDate(ctx, activityID, scheduledDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByActivityAndScheduledDate", reflect.TypeOf((*MockExecutionRepository)(nil).FindByActivityAndScheduledDate), ctx, activityID, scheduledDate)
}

// GetByID mocks base method.
func (m *MockExecutionRepository) GetByID(ctx context.Context, id domain0.ID) (domain.Execution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.Execution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockExecutionRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockExecutionRepository)(nil).GetByID), ctx, id)
}

// MarkCompleted mocks base method.
func (m *MockExecutionRepository) MarkCompleted(ctx context.Context, id domain0.ID, completedBy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkCompleted", ctx, id, completedBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkCompleted indicates an expected call of MarkCompleted.
func (mr *MockExecutionRepositoryMockRecorder) MarkCompleted(ctx, id, completedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkCompleted", reflect.TypeOf((*MockExecutionRepository)(nil).MarkCompleted), ctx, id, completedBy)
}

// Update mocks base method.
func (m *MockExecutionRepository) Update(ctx context.Context, execution domain.Execution) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, execution)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockExecutionRepositoryMockRecorder) Update(ctx, execution any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockExecutionRepository)(nil).Update), ctx, execution)
}
