// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"log/slog"
	"os"
	"sync"
	"time"
	"zensor-server/cmd/config"
	"zensor-server/internal/control_plane/httpapi"
	"zensor-server/internal/control_plane/persistence"
	"zensor-server/internal/control_plane/usecases"
	"zensor-server/internal/data_plane/workers"
	"zensor-server/internal/infra/async"
	"zensor-server/internal/infra/cache"
	"zensor-server/internal/infra/mqtt"
	"zensor-server/internal/infra/notification"
	"zensor-server/internal/infra/pubsub"
	"zensor-server/internal/infra/replication"
	"zensor-server/internal/infra/replication/handlers"
	"zensor-server/internal/infra/sql"
	httpapi2 "zensor-server/internal/maintenance/httpapi"
	persistence2 "zensor-server/internal/maintenance/persistence"
	usecases2 "zensor-server/internal/maintenance/usecases"
)

// Injectors from common.go:

func InitializeTenantConfigurationHandler() (*handlers.TenantConfigurationHandler, error) {
	appConfig := provideAppConfig()
	orm := provideDatabase(appConfig)
	tenantConfigurationHandler := handlers.NewTenantConfigurationHandler(orm)
	return tenantConfigurationHandler, nil
}

func InitializeUserHandler() (*handlers.UserHandler, error) {
	appConfig := provideAppConfig()
	orm := provideDatabase(appConfig)
	userHandler := handlers.NewUserHandler(orm)
	return userHandler, nil
}

// Injectors from control_plane.go:

func InitializeEvaluationRuleController() (*httpapi.EvaluationRuleController, error) {
	appConfig := provideAppConfig()
	publisherFactory := providePublisherFactoryForEnvironment(appConfig)
	orm := provideDatabase(appConfig)
	evaluationRuleRepository, err := persistence.NewEvaluationRuleRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleEvaluationRuleService := usecases.NewEvaluationRuleService(evaluationRuleRepository)
	simpleDeviceRepository, err := persistence.NewDeviceRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleCommandRepository, err := persistence.NewCommandRepository(orm, publisherFactory)
	if err != nil {
		return nil, err
	}
	simpleDeviceService := usecases.NewDeviceService(simpleDeviceRepository, simpleCommandRepository)
	evaluationRuleController := httpapi.NewEvaluationRuleController(simpleEvaluationRuleService, simpleDeviceService)
	return evaluationRuleController, nil
}

func InitializeDeviceController() (*httpapi.DeviceController, error) {
	appConfig := provideAppConfig()
	publisherFactory := providePublisherFactoryForEnvironment(appConfig)
	orm := provideDatabase(appConfig)
	simpleDeviceRepository, err := persistence.NewDeviceRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleCommandRepository, err := persistence.NewCommandRepository(orm, publisherFactory)
	if err != nil {
		return nil, err
	}
	simpleDeviceService := usecases.NewDeviceService(simpleDeviceRepository, simpleCommandRepository)
	deviceController := httpapi.NewDeviceController(simpleDeviceService)
	return deviceController, nil
}

func InitializeTaskController() (*httpapi.TaskController, error) {
	appConfig := provideAppConfig()
	factory := providePubSubFactory(appConfig)
	publisherFactory := providePublisherFactory(factory)
	orm := provideDatabase(appConfig)
	simpleTaskRepository, err := persistence.NewTaskRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleCommandRepository, err := persistence.NewCommandRepository(orm, publisherFactory)
	if err != nil {
		return nil, err
	}
	simpleDeviceRepository, err := persistence.NewDeviceRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleTaskService := usecases.NewTaskService(simpleTaskRepository, simpleCommandRepository, simpleDeviceRepository)
	simpleDeviceService := usecases.NewDeviceService(simpleDeviceRepository, simpleCommandRepository)
	taskController := httpapi.NewTaskController(simpleTaskService, simpleDeviceService)
	return taskController, nil
}

func InitializeScheduledTaskController() (*httpapi.ScheduledTaskController, error) {
	appConfig := provideAppConfig()
	publisherFactory := providePublisherFactoryForEnvironment(appConfig)
	orm := provideDatabase(appConfig)
	simpleScheduledTaskRepository, err := persistence.NewScheduledTaskRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleScheduledTaskService := usecases.NewScheduledTaskService(simpleScheduledTaskRepository)
	simpleDeviceRepository, err := persistence.NewDeviceRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleCommandRepository, err := persistence.NewCommandRepository(orm, publisherFactory)
	if err != nil {
		return nil, err
	}
	simpleDeviceService := usecases.NewDeviceService(simpleDeviceRepository, simpleCommandRepository)
	simpleTenantRepository, err := persistence.NewTenantRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleTenantService := usecases.NewTenantService(simpleTenantRepository, simpleDeviceService)
	simpleTaskRepository, err := persistence.NewTaskRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleTaskService := usecases.NewTaskService(simpleTaskRepository, simpleCommandRepository, simpleDeviceRepository)
	scheduledTaskController := httpapi.NewScheduledTaskController(simpleScheduledTaskService, simpleDeviceService, simpleTenantService, simpleTaskService)
	return scheduledTaskController, nil
}

func InitializeScheduledTaskWorker(broker async.InternalBroker) (*usecases.ScheduledTaskWorker, error) {
	ticker := provideTicker()
	appConfig := provideAppConfig()
	publisherFactory := providePublisherFactoryForEnvironment(appConfig)
	orm := provideDatabase(appConfig)
	simpleScheduledTaskRepository, err := persistence.NewScheduledTaskRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleTaskRepository, err := persistence.NewTaskRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleCommandRepository, err := persistence.NewCommandRepository(orm, publisherFactory)
	if err != nil {
		return nil, err
	}
	simpleDeviceRepository, err := persistence.NewDeviceRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleTaskService := usecases.NewTaskService(simpleTaskRepository, simpleCommandRepository, simpleDeviceRepository)
	simpleDeviceService := usecases.NewDeviceService(simpleDeviceRepository, simpleCommandRepository)
	simpleTenantConfigurationRepository, err := persistence.NewTenantConfigurationRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleUserRepository, err := persistence.NewUserRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleTenantRepository, err := persistence.NewTenantRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleUserService := usecases.NewUserService(simpleUserRepository, simpleTenantRepository)
	simpleTenantConfigurationService := usecases.NewTenantConfigurationService(simpleTenantConfigurationRepository, simpleUserService)
	scheduledTaskWorker := usecases.NewScheduledTaskWorker(ticker, simpleScheduledTaskRepository, simpleTaskService, simpleDeviceService, simpleTenantConfigurationService, broker)
	return scheduledTaskWorker, nil
}

func InitializeTenantController() (*httpapi.TenantController, error) {
	appConfig := provideAppConfig()
	publisherFactory := providePublisherFactoryForEnvironment(appConfig)
	orm := provideDatabase(appConfig)
	simpleTenantRepository, err := persistence.NewTenantRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleDeviceRepository, err := persistence.NewDeviceRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleCommandRepository, err := persistence.NewCommandRepository(orm, publisherFactory)
	if err != nil {
		return nil, err
	}
	simpleDeviceService := usecases.NewDeviceService(simpleDeviceRepository, simpleCommandRepository)
	simpleTenantService := usecases.NewTenantService(simpleTenantRepository, simpleDeviceService)
	tenantController := httpapi.NewTenantController(simpleTenantService)
	return tenantController, nil
}

func InitializeTenantConfigurationController() (*httpapi.TenantConfigurationController, error) {
	appConfig := provideAppConfig()
	publisherFactory := providePublisherFactoryForEnvironment(appConfig)
	orm := provideDatabase(appConfig)
	simpleTenantConfigurationRepository, err := persistence.NewTenantConfigurationRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleUserRepository, err := persistence.NewUserRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleTenantRepository, err := persistence.NewTenantRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleUserService := usecases.NewUserService(simpleUserRepository, simpleTenantRepository)
	simpleTenantConfigurationService := usecases.NewTenantConfigurationService(simpleTenantConfigurationRepository, simpleUserService)
	tenantConfigurationController := httpapi.NewTenantConfigurationController(simpleTenantConfigurationService)
	return tenantConfigurationController, nil
}

func InitializeUserController() (*httpapi.UserController, error) {
	appConfig := provideAppConfig()
	publisherFactory := providePublisherFactoryForEnvironment(appConfig)
	orm := provideDatabase(appConfig)
	simpleUserRepository, err := persistence.NewUserRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleTenantRepository, err := persistence.NewTenantRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleUserService := usecases.NewUserService(simpleUserRepository, simpleTenantRepository)
	userController := httpapi.NewUserController(simpleUserService)
	return userController, nil
}

func InitializeDeviceService() (usecases.DeviceService, error) {
	appConfig := provideAppConfig()
	publisherFactory := providePublisherFactoryForEnvironment(appConfig)
	orm := provideDatabase(appConfig)
	simpleDeviceRepository, err := persistence.NewDeviceRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleCommandRepository, err := persistence.NewCommandRepository(orm, publisherFactory)
	if err != nil {
		return nil, err
	}
	simpleDeviceService := usecases.NewDeviceService(simpleDeviceRepository, simpleCommandRepository)
	return simpleDeviceService, nil
}

func InitializeLoraIntegrationWorker(ticker *time.Ticker, mqttClient mqtt.Client, broker async.InternalBroker, consumerFactory pubsub.ConsumerFactory) (*workers.LoraIntegrationWorker, error) {
	appConfig := provideAppConfig()
	publisherFactory := providePublisherFactoryForEnvironment(appConfig)
	orm := provideDatabase(appConfig)
	simpleDeviceRepository, err := persistence.NewDeviceRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleCommandRepository, err := persistence.NewCommandRepository(orm, publisherFactory)
	if err != nil {
		return nil, err
	}
	simpleDeviceService := usecases.NewDeviceService(simpleDeviceRepository, simpleCommandRepository)
	usecasesDeviceStateCacheService := provideDeviceStateCacheService()
	loraIntegrationWorker := workers.NewLoraIntegrationWorker(ticker, simpleDeviceService, usecasesDeviceStateCacheService, mqttClient, broker, consumerFactory)
	return loraIntegrationWorker, nil
}

func InitializeCommandWorker(broker async.InternalBroker) (*usecases.CommandWorker, error) {
	ticker := provideTicker()
	appConfig := provideAppConfig()
	orm := provideDatabase(appConfig)
	publisherFactory := providePublisherFactoryForEnvironment(appConfig)
	simpleCommandRepository, err := persistence.NewCommandRepository(orm, publisherFactory)
	if err != nil {
		return nil, err
	}
	commandWorker := usecases.NewCommandWorker(ticker, simpleCommandRepository, broker)
	return commandWorker, nil
}

func InitializeNotificationWorker(broker async.InternalBroker) (*usecases.NotificationWorker, error) {
	ticker := provideTicker()
	appConfig := provideAppConfig()
	notificationClient := provideNotificationClient(appConfig)
	publisherFactory := providePublisherFactoryForEnvironment(appConfig)
	orm := provideDatabase(appConfig)
	simpleDeviceRepository, err := persistence.NewDeviceRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleCommandRepository, err := persistence.NewCommandRepository(orm, publisherFactory)
	if err != nil {
		return nil, err
	}
	simpleDeviceService := usecases.NewDeviceService(simpleDeviceRepository, simpleCommandRepository)
	simpleTenantConfigurationRepository, err := persistence.NewTenantConfigurationRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleUserRepository, err := persistence.NewUserRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleTenantRepository, err := persistence.NewTenantRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleUserService := usecases.NewUserService(simpleUserRepository, simpleTenantRepository)
	simpleTenantConfigurationService := usecases.NewTenantConfigurationService(simpleTenantConfigurationRepository, simpleUserService)
	simpleTaskRepository, err := persistence.NewTaskRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleTaskService := usecases.NewTaskService(simpleTaskRepository, simpleCommandRepository, simpleDeviceRepository)
	notificationWorker := usecases.NewNotificationWorker(ticker, notificationClient, simpleDeviceService, simpleTenantConfigurationService, simpleTaskService, broker)
	return notificationWorker, nil
}

func InitializeDeviceMessageWebSocketController(broker async.InternalBroker) (*httpapi.DeviceMessageWebSocketController, error) {
	usecasesDeviceStateCacheService := provideDeviceStateCacheService()
	deviceMessageWebSocketController := httpapi.NewDeviceMessageWebSocketController(broker, usecasesDeviceStateCacheService)
	return deviceMessageWebSocketController, nil
}

func InitializeDeviceSpecificWebSocketController(broker async.InternalBroker) (*httpapi.DeviceSpecificWebSocketController, error) {
	usecasesDeviceStateCacheService := provideDeviceStateCacheService()
	deviceSpecificWebSocketController := httpapi.NewDeviceSpecificWebSocketController(broker, usecasesDeviceStateCacheService)
	return deviceSpecificWebSocketController, nil
}

func InitializeReplicationService() (*replication.Service, error) {
	consumerFactory := provideMemoryConsumerFactory()
	appConfig := provideAppConfig()
	orm := provideDatabase(appConfig)
	service := replication.NewService(consumerFactory, orm)
	return service, nil
}

func InitializeDeviceHandler() (*handlers.DeviceHandler, error) {
	appConfig := provideAppConfig()
	orm := provideDatabase(appConfig)
	deviceHandler := handlers.NewDeviceHandler(orm)
	return deviceHandler, nil
}

func InitializeTenantHandler() (*handlers.TenantHandler, error) {
	appConfig := provideAppConfig()
	orm := provideDatabase(appConfig)
	tenantHandler := handlers.NewTenantHandler(orm)
	return tenantHandler, nil
}

func InitializeTaskHandler() (*handlers.TaskHandler, error) {
	appConfig := provideAppConfig()
	orm := provideDatabase(appConfig)
	taskHandler := handlers.NewTaskHandler(orm)
	return taskHandler, nil
}

func InitializeCommandHandler() (*handlers.CommandHandler, error) {
	appConfig := provideAppConfig()
	orm := provideDatabase(appConfig)
	commandHandler := handlers.NewCommandHandler(orm)
	return commandHandler, nil
}

func InitializeScheduledTaskHandler() (*handlers.ScheduledTaskHandler, error) {
	appConfig := provideAppConfig()
	orm := provideDatabase(appConfig)
	scheduledTaskHandler := handlers.NewScheduledTaskHandler(orm)
	return scheduledTaskHandler, nil
}

func InitializePushTokenController() (*httpapi.PushTokenController, error) {
	appConfig := provideAppConfig()
	orm := provideDatabase(appConfig)
	simplePushTokenRepository, err := persistence.NewPushTokenRepository(orm)
	if err != nil {
		return nil, err
	}
	simplePushTokenService := usecases.NewPushTokenService(simplePushTokenRepository)
	pushTokenController := httpapi.NewPushTokenController(simplePushTokenService)
	return pushTokenController, nil
}

func InitializePushNotificationWorkerFactory(broker async.InternalBroker) (*usecases.PushNotificationWorkerFactory, error) {
	appConfig := provideAppConfig()
	notificationClient := provideCompositeNotificationClient(appConfig)
	orm := provideDatabase(appConfig)
	simplePushTokenRepository, err := persistence.NewPushTokenRepository(orm)
	if err != nil {
		return nil, err
	}
	simplePushTokenService := usecases.NewPushTokenService(simplePushTokenRepository)
	publisherFactory := providePublisherFactoryForEnvironment(appConfig)
	simpleUserRepository, err := persistence.NewUserRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleTenantRepository, err := persistence.NewTenantRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleUserService := usecases.NewUserService(simpleUserRepository, simpleTenantRepository)
	pushNotificationWorkerFactory := usecases.NewPushNotificationWorkerFactory(broker, notificationClient, simplePushTokenService, simpleUserService)
	return pushNotificationWorkerFactory, nil
}

// Injectors from maintenance.go:

func InitializeMaintenanceActivityController() (*httpapi2.ActivityController, error) {
	appConfig := provideAppConfig()
	publisherFactory := providePublisherFactoryForEnvironment(appConfig)
	orm := provideDatabase(appConfig)
	simpleActivityRepository, err := persistence2.NewActivityRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleTenantRepository, err := persistence.NewTenantRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleDeviceRepository, err := persistence.NewDeviceRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleCommandRepository, err := persistence.NewCommandRepository(orm, publisherFactory)
	if err != nil {
		return nil, err
	}
	simpleDeviceService := usecases.NewDeviceService(simpleDeviceRepository, simpleCommandRepository)
	simpleTenantService := usecases.NewTenantService(simpleTenantRepository, simpleDeviceService)
	simpleActivityService := usecases2.NewActivityService(simpleActivityRepository, simpleTenantService)
	activityController := httpapi2.NewActivityController(simpleActivityService)
	return activityController, nil
}

func InitializeMaintenanceExecutionController() (*httpapi2.ExecutionController, error) {
	appConfig := provideAppConfig()
	publisherFactory := providePublisherFactoryForEnvironment(appConfig)
	orm := provideDatabase(appConfig)
	simpleExecutionRepository, err := persistence2.NewExecutionRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleActivityRepository, err := persistence2.NewActivityRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleExecutionService := usecases2.NewExecutionService(simpleExecutionRepository, simpleActivityRepository)
	simpleTenantRepository, err := persistence.NewTenantRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleDeviceRepository, err := persistence.NewDeviceRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleCommandRepository, err := persistence.NewCommandRepository(orm, publisherFactory)
	if err != nil {
		return nil, err
	}
	simpleDeviceService := usecases.NewDeviceService(simpleDeviceRepository, simpleCommandRepository)
	simpleTenantService := usecases.NewTenantService(simpleTenantRepository, simpleDeviceService)
	simpleActivityService := usecases2.NewActivityService(simpleActivityRepository, simpleTenantService)
	executionController := httpapi2.NewExecutionController(simpleExecutionService, simpleActivityService)
	return executionController, nil
}

func InitializeExecutionWorker(broker async.InternalBroker) (*usecases2.ExecutionWorker, error) {
	ticker := provideExecutionWorkerTicker()
	appConfig := provideAppConfig()
	publisherFactory := providePublisherFactoryForEnvironment(appConfig)
	orm := provideDatabase(appConfig)
	simpleActivityRepository, err := persistence2.NewActivityRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleExecutionRepository, err := persistence2.NewExecutionRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleExecutionService := usecases2.NewExecutionService(simpleExecutionRepository, simpleActivityRepository)
	simpleTenantRepository, err := persistence.NewTenantRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleDeviceRepository, err := persistence.NewDeviceRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleCommandRepository, err := persistence.NewCommandRepository(orm, publisherFactory)
	if err != nil {
		return nil, err
	}
	simpleDeviceService := usecases.NewDeviceService(simpleDeviceRepository, simpleCommandRepository)
	simpleTenantService := usecases.NewTenantService(simpleTenantRepository, simpleDeviceService)
	simpleTenantConfigurationRepository, err := persistence.NewTenantConfigurationRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleUserRepository, err := persistence.NewUserRepository(publisherFactory, orm)
	if err != nil {
		return nil, err
	}
	simpleUserService := usecases.NewUserService(simpleUserRepository, simpleTenantRepository)
	simpleTenantConfigurationService := usecases.NewTenantConfigurationService(simpleTenantConfigurationRepository, simpleUserService)
	executionWorker := usecases2.NewExecutionWorker(ticker, simpleActivityRepository, simpleExecutionRepository, simpleExecutionService, simpleTenantService, simpleTenantConfigurationService, broker)
	return executionWorker, nil
}

// control_plane.go:

var DeviceServiceSet = wire.NewSet(
	provideDatabase, persistence.NewDeviceRepository, wire.Bind(new(usecases.DeviceRepository), new(*persistence.SimpleDeviceRepository)), providePublisherFactoryForEnvironment, persistence.NewCommandRepository, wire.Bind(new(usecases.CommandRepository), new(*persistence.SimpleCommandRepository)), usecases.NewDeviceService,
)

func providePubSubFactory(config2 config.AppConfig) *pubsub.Factory {
	env, ok := os.LookupEnv("ENV")
	if !ok {
		env = "production"
	}

	return pubsub.NewFactory(pubsub.FactoryOptions{
		Environment:       env,
		KafkaBrokers:      config2.Kafka.Brokers,
		ConsumerGroup:     "zensor-server",
		SchemaRegistryURL: config2.Kafka.SchemaRegistry,
	})
}

func providePublisherFactory(factory *pubsub.Factory) pubsub.PublisherFactory {
	return factory.GetPublisherFactory()
}

func provideKafkaPublisherFactoryOptions(config2 config.AppConfig) pubsub.KafkaPublisherFactoryOptions {
	return pubsub.KafkaPublisherFactoryOptions{
		Brokers:           config2.Kafka.Brokers,
		SchemaRegistryURL: config2.Kafka.SchemaRegistry,
	}
}

func provideAppConfig() config.AppConfig {
	return config.LoadConfig()
}

func provideDatabase(config2 config.AppConfig) sql.ORM {
	env, ok := os.LookupEnv("ENV")
	if !ok {
		env = "production"
	}

	if env == "local" {
		orm, err := sql.NewMemoryORM("migrations")
		if err != nil {
			panic(err)
		}

		return orm
	}

	orm, err := sql.NewPosgreORMWithTimeout(config2.Postgresql.DSN, config2.Postgresql.QueryTimeout)
	if err != nil {
		panic(err)
	}

	return orm
}

func provideTicker() *time.Ticker {
	ticker := time.NewTicker(30 * time.Second)
	return ticker
}

func provideNotificationClient(config2 config.AppConfig) notification.NotificationClient {
	mailerSendConfig := notification.MailerSendConfig{
		APIKey:    config2.MailerSend.APIKey,
		FromEmail: config2.MailerSend.FromEmail,
		FromName:  config2.MailerSend.FromName,
	}

	return notification.NewMailerSendClient(mailerSendConfig)
}

func provideMemoryConsumerFactory() pubsub.ConsumerFactory {
	env, ok := os.LookupEnv("ENV")
	if !ok {
		env = "production"
	}

	if env == "local" {
		return pubsub.NewMemoryConsumerFactory("replicator")
	}

	return nil
}

func providePublisherFactoryForEnvironment(config2 config.AppConfig) pubsub.PublisherFactory {
	env, ok := os.LookupEnv("ENV")
	if !ok {
		env = "production"
	}

	if env == "local" {
		return pubsub.NewMemoryPublisherFactory()
	}

	kafkaOptions := provideKafkaPublisherFactoryOptions(config2)
	return pubsub.NewKafkaPublisherFactory(kafkaOptions)
}

var (
	deviceStateCacheService usecases.DeviceStateCacheService
	deviceStateCacheOnce    sync.Once
)

func provideDeviceStateCacheService() usecases.DeviceStateCacheService {
	deviceStateCacheOnce.Do(func() {
		appConfig := provideAppConfig()

		redisCache, err := cache.NewRedisCache(&cache.RedisConfig{
			Addr:     appConfig.Redis.Addr,
			Password: appConfig.Redis.Password,
			DB:       appConfig.Redis.DB,
		})
		if err != nil {
			slog.Error("failed to create Redis cache", slog.String("error", err.Error()))
			deviceStateCacheService = persistence.NewSimpleDeviceStateCacheService()
			slog.Info("falling back to simple device state cache service")
			return
		}

		deviceStateCacheService, err = persistence.NewRedisDeviceStateCacheService(&persistence.RedisDeviceStateCacheConfig{
			Cache:      redisCache,
			KeyPrefix:  "device_state:",
			DefaultTTL: 24 * time.Hour,
		})
		if err != nil {
			slog.Error("failed to create Redis device state cache service", slog.String("error", err.Error()))
			deviceStateCacheService = persistence.NewSimpleDeviceStateCacheService()
			slog.Info("falling back to simple device state cache service")
			return
		}
		slog.Info("Redis device state cache service singleton created")
	})
	return deviceStateCacheService
}

func InitializeMetricWorkerFactory(broker async.InternalBroker) *usecases.MetricWorkerFactory {
	return usecases.NewMetricWorkerFactory(broker)
}

func provideCompositeNotificationClient(config2 config.AppConfig) notification.NotificationClient {
	mailerSendConfig := notification.MailerSendConfig{
		APIKey:    config2.MailerSend.APIKey,
		FromEmail: config2.MailerSend.FromEmail,
		FromName:  config2.MailerSend.FromName,
	}
	emailClient := notification.NewMailerSendClient(mailerSendConfig)

	fcmConfig := notification.FCMConfig{
		ProjectID:   config2.FCM.ProjectID,
		AccessToken: config2.FCM.AccessToken,
	}
	pushClient := notification.NewFCMClient(fcmConfig)

	return notification.NewCompositeNotificationClient(emailClient, pushClient)
}

// maintenance.go:

func provideExecutionWorkerTicker() *time.Ticker {
	return time.NewTicker(5 * time.Minute)
}
