// Code generated by MockGen. DO NOT EDIT.
// Source: ./api.go
//
// Generated by this command:
//
//	mockgen -source=./api.go -destination=../../../test/unit/doubles/shared_kernel/usecases/api_mock.go -package=usecases
//

// Package usecases is a generated GoMock package.
package usecases

import (
	context "context"
	reflect "reflect"
	domain "zensor-server/internal/shared_kernel/domain"
	usecases "zensor-server/internal/shared_kernel/usecases"

	gomock "go.uber.org/mock/gomock"
)

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
	isgomock struct{}
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// AssociateTenants mocks base method.
func (m *MockUserService) AssociateTenants(arg0 context.Context, arg1 domain.ID, arg2 []domain.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssociateTenants", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssociateTenants indicates an expected call of AssociateTenants.
func (mr *MockUserServiceMockRecorder) AssociateTenants(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssociateTenants", reflect.TypeOf((*MockUserService)(nil).AssociateTenants), arg0, arg1, arg2)
}

// FindByTenant mocks base method.
func (m *MockUserService) FindByTenant(arg0 context.Context, arg1 domain.ID) ([]domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTenant", arg0, arg1)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTenant indicates an expected call of FindByTenant.
func (mr *MockUserServiceMockRecorder) FindByTenant(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTenant", reflect.TypeOf((*MockUserService)(nil).FindByTenant), arg0, arg1)
}

// GetUser mocks base method.
func (m *MockUserService) GetUser(arg0 context.Context, arg1 domain.ID) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", arg0, arg1)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUserServiceMockRecorder) GetUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUserService)(nil).GetUser), arg0, arg1)
}

// MockTenantConfigurationService is a mock of TenantConfigurationService interface.
type MockTenantConfigurationService struct {
	ctrl     *gomock.Controller
	recorder *MockTenantConfigurationServiceMockRecorder
	isgomock struct{}
}

// MockTenantConfigurationServiceMockRecorder is the mock recorder for MockTenantConfigurationService.
type MockTenantConfigurationServiceMockRecorder struct {
	mock *MockTenantConfigurationService
}

// NewMockTenantConfigurationService creates a new mock instance.
func NewMockTenantConfigurationService(ctrl *gomock.Controller) *MockTenantConfigurationService {
	mock := &MockTenantConfigurationService{ctrl: ctrl}
	mock.recorder = &MockTenantConfigurationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantConfigurationService) EXPECT() *MockTenantConfigurationServiceMockRecorder {
	return m.recorder
}

// GetOrCreateTenantConfiguration mocks base method.
func (m *MockTenantConfigurationService) GetOrCreateTenantConfiguration(ctx context.Context, tenant domain.Tenant, defaultTimezone string) (domain.TenantConfiguration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrCreateTenantConfiguration", ctx, tenant, defaultTimezone)
	ret0, _ := ret[0].(domain.TenantConfiguration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrCreateTenantConfiguration indicates an expected call of GetOrCreateTenantConfiguration.
func (mr *MockTenantConfigurationServiceMockRecorder) GetOrCreateTenantConfiguration(ctx, tenant, defaultTimezone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrCreateTenantConfiguration", reflect.TypeOf((*MockTenantConfigurationService)(nil).GetOrCreateTenantConfiguration), ctx, tenant, defaultTimezone)
}

// GetTenantConfiguration mocks base method.
func (m *MockTenantConfigurationService) GetTenantConfiguration(ctx context.Context, tenant domain.Tenant) (domain.TenantConfiguration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantConfiguration", ctx, tenant)
	ret0, _ := ret[0].(domain.TenantConfiguration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenantConfiguration indicates an expected call of GetTenantConfiguration.
func (mr *MockTenantConfigurationServiceMockRecorder) GetTenantConfiguration(ctx, tenant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantConfiguration", reflect.TypeOf((*MockTenantConfigurationService)(nil).GetTenantConfiguration), ctx, tenant)
}

// UpsertTenantConfiguration mocks base method.
func (m *MockTenantConfigurationService) UpsertTenantConfiguration(ctx context.Context, userEmail string, config domain.TenantConfiguration) (domain.TenantConfiguration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTenantConfiguration", ctx, userEmail, config)
	ret0, _ := ret[0].(domain.TenantConfiguration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertTenantConfiguration indicates an expected call of UpsertTenantConfiguration.
func (mr *MockTenantConfigurationServiceMockRecorder) UpsertTenantConfiguration(ctx, userEmail, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTenantConfiguration", reflect.TypeOf((*MockTenantConfigurationService)(nil).UpsertTenantConfiguration), ctx, userEmail, config)
}

// MockTenantService is a mock of TenantService interface.
type MockTenantService struct {
	ctrl     *gomock.Controller
	recorder *MockTenantServiceMockRecorder
	isgomock struct{}
}

// MockTenantServiceMockRecorder is the mock recorder for MockTenantService.
type MockTenantServiceMockRecorder struct {
	mock *MockTenantService
}

// NewMockTenantService creates a new mock instance.
func NewMockTenantService(ctrl *gomock.Controller) *MockTenantService {
	mock := &MockTenantService{ctrl: ctrl}
	mock.recorder = &MockTenantServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantService) EXPECT() *MockTenantServiceMockRecorder {
	return m.recorder
}

// ActivateTenant mocks base method.
func (m *MockTenantService) ActivateTenant(ctx context.Context, id domain.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateTenant", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateTenant indicates an expected call of ActivateTenant.
func (mr *MockTenantServiceMockRecorder) ActivateTenant(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateTenant", reflect.TypeOf((*MockTenantService)(nil).ActivateTenant), ctx, id)
}

// AdoptDevice mocks base method.
func (m *MockTenantService) AdoptDevice(ctx context.Context, tenantID, deviceID domain.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdoptDevice", ctx, tenantID, deviceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdoptDevice indicates an expected call of AdoptDevice.
func (mr *MockTenantServiceMockRecorder) AdoptDevice(ctx, tenantID, deviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdoptDevice", reflect.TypeOf((*MockTenantService)(nil).AdoptDevice), ctx, tenantID, deviceID)
}

// CreateTenant mocks base method.
func (m *MockTenantService) CreateTenant(ctx context.Context, tenant domain.Tenant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTenant", ctx, tenant)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTenant indicates an expected call of CreateTenant.
func (mr *MockTenantServiceMockRecorder) CreateTenant(ctx, tenant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTenant", reflect.TypeOf((*MockTenantService)(nil).CreateTenant), ctx, tenant)
}

// DeactivateTenant mocks base method.
func (m *MockTenantService) DeactivateTenant(ctx context.Context, id domain.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateTenant", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateTenant indicates an expected call of DeactivateTenant.
func (mr *MockTenantServiceMockRecorder) DeactivateTenant(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateTenant", reflect.TypeOf((*MockTenantService)(nil).DeactivateTenant), ctx, id)
}

// GetTenant mocks base method.
func (m *MockTenantService) GetTenant(ctx context.Context, id domain.ID) (domain.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenant", ctx, id)
	ret0, _ := ret[0].(domain.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenant indicates an expected call of GetTenant.
func (mr *MockTenantServiceMockRecorder) GetTenant(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenant", reflect.TypeOf((*MockTenantService)(nil).GetTenant), ctx, id)
}

// GetTenantByName mocks base method.
func (m *MockTenantService) GetTenantByName(ctx context.Context, name string) (domain.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantByName", ctx, name)
	ret0, _ := ret[0].(domain.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenantByName indicates an expected call of GetTenantByName.
func (mr *MockTenantServiceMockRecorder) GetTenantByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantByName", reflect.TypeOf((*MockTenantService)(nil).GetTenantByName), ctx, name)
}

// ListTenantDevices mocks base method.
func (m *MockTenantService) ListTenantDevices(ctx context.Context, tenantID domain.ID, pagination usecases.Pagination) ([]domain.Device, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTenantDevices", ctx, tenantID, pagination)
	ret0, _ := ret[0].([]domain.Device)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTenantDevices indicates an expected call of ListTenantDevices.
func (mr *MockTenantServiceMockRecorder) ListTenantDevices(ctx, tenantID, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTenantDevices", reflect.TypeOf((*MockTenantService)(nil).ListTenantDevices), ctx, tenantID, pagination)
}

// ListTenants mocks base method.
func (m *MockTenantService) ListTenants(ctx context.Context, includeDeleted bool, pagination usecases.Pagination) ([]domain.Tenant, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTenants", ctx, includeDeleted, pagination)
	ret0, _ := ret[0].([]domain.Tenant)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTenants indicates an expected call of ListTenants.
func (mr *MockTenantServiceMockRecorder) ListTenants(ctx, includeDeleted, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTenants", reflect.TypeOf((*MockTenantService)(nil).ListTenants), ctx, includeDeleted, pagination)
}

// SoftDeleteTenant mocks base method.
func (m *MockTenantService) SoftDeleteTenant(ctx context.Context, id domain.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteTenant", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteTenant indicates an expected call of SoftDeleteTenant.
func (mr *MockTenantServiceMockRecorder) SoftDeleteTenant(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteTenant", reflect.TypeOf((*MockTenantService)(nil).SoftDeleteTenant), ctx, id)
}

// UpdateTenant mocks base method.
func (m *MockTenantService) UpdateTenant(ctx context.Context, tenant domain.Tenant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTenant", ctx, tenant)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTenant indicates an expected call of UpdateTenant.
func (mr *MockTenantServiceMockRecorder) UpdateTenant(ctx, tenant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTenant", reflect.TypeOf((*MockTenantService)(nil).UpdateTenant), ctx, tenant)
}

// MockPushTokenService is a mock of PushTokenService interface.
type MockPushTokenService struct {
	ctrl     *gomock.Controller
	recorder *MockPushTokenServiceMockRecorder
	isgomock struct{}
}

// MockPushTokenServiceMockRecorder is the mock recorder for MockPushTokenService.
type MockPushTokenServiceMockRecorder struct {
	mock *MockPushTokenService
}

// NewMockPushTokenService creates a new mock instance.
func NewMockPushTokenService(ctrl *gomock.Controller) *MockPushTokenService {
	mock := &MockPushTokenService{ctrl: ctrl}
	mock.recorder = &MockPushTokenServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPushTokenService) EXPECT() *MockPushTokenServiceMockRecorder {
	return m.recorder
}

// GetTokenByUserID mocks base method.
func (m *MockPushTokenService) GetTokenByUserID(ctx context.Context, userID domain.ID) (domain.PushToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenByUserID", ctx, userID)
	ret0, _ := ret[0].(domain.PushToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenByUserID indicates an expected call of GetTokenByUserID.
func (mr *MockPushTokenServiceMockRecorder) GetTokenByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenByUserID", reflect.TypeOf((*MockPushTokenService)(nil).GetTokenByUserID), ctx, userID)
}

// RegisterToken mocks base method.
func (m *MockPushTokenService) RegisterToken(ctx context.Context, userID domain.ID, token, platform string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterToken", ctx, userID, token, platform)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterToken indicates an expected call of RegisterToken.
func (mr *MockPushTokenServiceMockRecorder) RegisterToken(ctx, userID, token, platform any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterToken", reflect.TypeOf((*MockPushTokenService)(nil).RegisterToken), ctx, userID, token, platform)
}

// UnregisterToken mocks base method.
func (m *MockPushTokenService) UnregisterToken(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnregisterToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnregisterToken indicates an expected call of UnregisterToken.
func (mr *MockPushTokenServiceMockRecorder) UnregisterToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnregisterToken", reflect.TypeOf((*MockPushTokenService)(nil).UnregisterToken), ctx, token)
}

// MockDeviceAdopter is a mock of DeviceAdopter interface.
type MockDeviceAdopter struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceAdopterMockRecorder
	isgomock struct{}
}

// MockDeviceAdopterMockRecorder is the mock recorder for MockDeviceAdopter.
type MockDeviceAdopterMockRecorder struct {
	mock *MockDeviceAdopter
}

// NewMockDeviceAdopter creates a new mock instance.
func NewMockDeviceAdopter(ctrl *gomock.Controller) *MockDeviceAdopter {
	mock := &MockDeviceAdopter{ctrl: ctrl}
	mock.recorder = &MockDeviceAdopterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceAdopter) EXPECT() *MockDeviceAdopterMockRecorder {
	return m.recorder
}

// AdoptDeviceToTenant mocks base method.
func (m *MockDeviceAdopter) AdoptDeviceToTenant(ctx context.Context, tenantID, deviceID domain.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdoptDeviceToTenant", ctx, tenantID, deviceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdoptDeviceToTenant indicates an expected call of AdoptDeviceToTenant.
func (mr *MockDeviceAdopterMockRecorder) AdoptDeviceToTenant(ctx, tenantID, deviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdoptDeviceToTenant", reflect.TypeOf((*MockDeviceAdopter)(nil).AdoptDeviceToTenant), ctx, tenantID, deviceID)
}

// DevicesByTenant mocks base method.
func (m *MockDeviceAdopter) DevicesByTenant(ctx context.Context, tenantID domain.ID, pagination usecases.Pagination) ([]domain.Device, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DevicesByTenant", ctx, tenantID, pagination)
	ret0, _ := ret[0].([]domain.Device)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DevicesByTenant indicates an expected call of DevicesByTenant.
func (mr *MockDeviceAdopterMockRecorder) DevicesByTenant(ctx, tenantID, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DevicesByTenant", reflect.TypeOf((*MockDeviceAdopter)(nil).DevicesByTenant), ctx, tenantID, pagination)
}
