// Code generated by MockGen. DO NOT EDIT.
// Source: internal/shared_kernel/usecases/auth_ports.go
//
// Generated by this command:
//
//	mockgen -source=internal/shared_kernel/usecases/auth_ports.go -destination=test/unit/doubles/shared_kernel/usecases/auth_ports_mock.go -package=usecases -mock_names=AllowedUserRepository=MockAllowedUserRepository,SessionStore=MockSessionStore,OAuthProvider=MockOAuthProvider,AuthService=MockAuthService
//

// Package usecases is a generated GoMock package.
package usecases

import (
	context "context"
	reflect "reflect"
	domain "zensor-server/internal/shared_kernel/domain"
	usecases "zensor-server/internal/shared_kernel/usecases"

	gomock "go.uber.org/mock/gomock"
)

// MockOAuthProvider is a mock of OAuthProvider interface.
type MockOAuthProvider struct {
	ctrl     *gomock.Controller
	recorder *MockOAuthProviderMockRecorder
	isgomock struct{}
}

// MockOAuthProviderMockRecorder is the mock recorder for MockOAuthProvider.
type MockOAuthProviderMockRecorder struct {
	mock *MockOAuthProvider
}

// NewMockOAuthProvider creates a new mock instance.
func NewMockOAuthProvider(ctrl *gomock.Controller) *MockOAuthProvider {
	mock := &MockOAuthProvider{ctrl: ctrl}
	mock.recorder = &MockOAuthProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOAuthProvider) EXPECT() *MockOAuthProviderMockRecorder {
	return m.recorder
}

// AuthCodeURL mocks base method.
func (m *MockOAuthProvider) AuthCodeURL(state string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthCodeURL", state)
	ret0, _ := ret[0].(string)
	return ret0
}

// AuthCodeURL indicates an expected call of AuthCodeURL.
func (mr *MockOAuthProviderMockRecorder) AuthCodeURL(state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthCodeURL", reflect.TypeOf((*MockOAuthProvider)(nil).AuthCodeURL), state)
}

// ExchangeCode mocks base method.
func (m *MockOAuthProvider) ExchangeCode(ctx context.Context, code string) (usecases.OAuthIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeCode", ctx, code)
	ret0, _ := ret[0].(usecases.OAuthIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeCode indicates an expected call of ExchangeCode.
func (mr *MockOAuthProviderMockRecorder) ExchangeCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeCode", reflect.TypeOf((*MockOAuthProvider)(nil).ExchangeCode), ctx, code)
}

// MockSessionStore is a mock of SessionStore interface.
type MockSessionStore struct {
	ctrl     *gomock.Controller
	recorder *MockSessionStoreMockRecorder
	isgomock struct{}
}

// MockSessionStoreMockRecorder is the mock recorder for MockSessionStore.
type MockSessionStoreMockRecorder struct {
	mock *MockSessionStore
}

// NewMockSessionStore creates a new mock instance.
func NewMockSessionStore(ctrl *gomock.Controller) *MockSessionStore {
	mock := &MockSessionStore{ctrl: ctrl}
	mock.recorder = &MockSessionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionStore) EXPECT() *MockSessionStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSessionStore) Create(ctx context.Context, session domain.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSessionStoreMockRecorder) Create(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionStore)(nil).Create), ctx, session)
}

// Delete mocks base method.
func (m *MockSessionStore) Delete(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSessionStoreMockRecorder) Delete(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSessionStore)(nil).Delete), ctx, sessionID)
}

// DeleteByUser mocks base method.
func (m *MockSessionStore) DeleteByUser(ctx context.Context, userID domain.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUser indicates an expected call of DeleteByUser.
func (mr *MockSessionStoreMockRecorder) DeleteByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUser", reflect.TypeOf((*MockSessionStore)(nil).DeleteByUser), ctx, userID)
}

// Get mocks base method.
func (m *MockSessionStore) Get(ctx context.Context, sessionID string) (domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, sessionID)
	ret0, _ := ret[0].(domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSessionStoreMockRecorder) Get(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSessionStore)(nil).Get), ctx, sessionID)
}

// MockAllowedUserRepository is a mock of AllowedUserRepository interface.
type MockAllowedUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAllowedUserRepositoryMockRecorder
	isgomock struct{}
}

// MockAllowedUserRepositoryMockRecorder is the mock recorder for MockAllowedUserRepository.
type MockAllowedUserRepositoryMockRecorder struct {
	mock *MockAllowedUserRepository
}

// NewMockAllowedUserRepository creates a new mock instance.
func NewMockAllowedUserRepository(ctrl *gomock.Controller) *MockAllowedUserRepository {
	mock := &MockAllowedUserRepository{ctrl: ctrl}
	mock.recorder = &MockAllowedUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAllowedUserRepository) EXPECT() *MockAllowedUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAllowedUserRepository) Create(arg0 context.Context, arg1 domain.AllowedUser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAllowedUserRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAllowedUserRepository)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockAllowedUserRepository) Delete(arg0 context.Context, arg1 domain.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAllowedUserRepositoryMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAllowedUserRepository)(nil).Delete), arg0, arg1)
}

// FindAll mocks base method.
func (m *MockAllowedUserRepository) FindAll(arg0 context.Context) ([]domain.AllowedUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", arg0)
	ret0, _ := ret[0].([]domain.AllowedUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockAllowedUserRepositoryMockRecorder) FindAll(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockAllowedUserRepository)(nil).FindAll), arg0)
}

// GetByEmail mocks base method.
func (m *MockAllowedUserRepository) GetByEmail(arg0 context.Context, arg1 string) (domain.AllowedUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", arg0, arg1)
	ret0, _ := ret[0].(domain.AllowedUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockAllowedUserRepositoryMockRecorder) GetByEmail(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockAllowedUserRepository)(nil).GetByEmail), arg0, arg1)
}

// GetByID mocks base method.
func (m *MockAllowedUserRepository) GetByID(arg0 context.Context, arg1 domain.ID) (domain.AllowedUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(domain.AllowedUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAllowedUserRepositoryMockRecorder) GetByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAllowedUserRepository)(nil).GetByID), arg0, arg1)
}

// Update mocks base method.
func (m *MockAllowedUserRepository) Update(arg0 context.Context, arg1 domain.AllowedUser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAllowedUserRepositoryMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAllowedUserRepository)(nil).Update), arg0, arg1)
}

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
	isgomock struct{}
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// AddAllowedUser mocks base method.
func (m *MockAuthService) AddAllowedUser(ctx context.Context, email string, isAdmin bool) (domain.AllowedUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAllowedUser", ctx, email, isAdmin)
	ret0, _ := ret[0].(domain.AllowedUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddAllowedUser indicates an expected call of AddAllowedUser.
func (mr *MockAuthServiceMockRecorder) AddAllowedUser(ctx, email, isAdmin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAllowedUser", reflect.TypeOf((*MockAuthService)(nil).AddAllowedUser), ctx, email, isAdmin)
}

// AuthCodeURL mocks base method.
func (m *MockAuthService) AuthCodeURL(state string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthCodeURL", state)
	ret0, _ := ret[0].(string)
	return ret0
}

// AuthCodeURL indicates an expected call of AuthCodeURL.
func (mr *MockAuthServiceMockRecorder) AuthCodeURL(state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthCodeURL", reflect.TypeOf((*MockAuthService)(nil).AuthCodeURL), state)
}

// BootstrapAdmin mocks base method.
func (m *MockAuthService) BootstrapAdmin(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BootstrapAdmin", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// BootstrapAdmin indicates an expected call of BootstrapAdmin.
func (mr *MockAuthServiceMockRecorder) BootstrapAdmin(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BootstrapAdmin", reflect.TypeOf((*MockAuthService)(nil).BootstrapAdmin), ctx, email)
}

// GetSession mocks base method.
func (m *MockAuthService) GetSession(ctx context.Context, sessionID string) (domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx, sessionID)
	ret0, _ := ret[0].(domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockAuthServiceMockRecorder) GetSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockAuthService)(nil).GetSession), ctx, sessionID)
}

// HandleCallback mocks base method.
func (m *MockAuthService) HandleCallback(ctx context.Context, code string) (domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleCallback", ctx, code)
	ret0, _ := ret[0].(domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleCallback indicates an expected call of HandleCallback.
func (mr *MockAuthServiceMockRecorder) HandleCallback(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleCallback", reflect.TypeOf((*MockAuthService)(nil).HandleCallback), ctx, code)
}

// ListAllowedUsers mocks base method.
func (m *MockAuthService) ListAllowedUsers(ctx context.Context) ([]domain.AllowedUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllowedUsers", ctx)
	ret0, _ := ret[0].([]domain.AllowedUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllowedUsers indicates an expected call of ListAllowedUsers.
func (mr *MockAuthServiceMockRecorder) ListAllowedUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllowedUsers", reflect.TypeOf((*MockAuthService)(nil).ListAllowedUsers), ctx)
}

// Logout mocks base method.
func (m *MockAuthService) Logout(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthServiceMockRecorder) Logout(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthService)(nil).Logout), ctx, sessionID)
}

// RemoveAllowedUser mocks base method.
func (m *MockAuthService) RemoveAllowedUser(ctx context.Context, id domain.ID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAllowedUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAllowedUser indicates an expected call of RemoveAllowedUser.
func (mr *MockAuthServiceMockRecorder) RemoveAllowedUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAllowedUser", reflect.TypeOf((*MockAuthService)(nil).RemoveAllowedUser), ctx, id)
}

// UpdateAllowedUser mocks base method.
func (m *MockAuthService) UpdateAllowedUser(ctx context.Context, id domain.ID, isAdmin bool) (domain.AllowedUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAllowedUser", ctx, id, isAdmin)
	ret0, _ := ret[0].(domain.AllowedUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAllowedUser indicates an expected call of UpdateAllowedUser.
func (mr *MockAuthServiceMockRecorder) UpdateAllowedUser(ctx, id, isAdmin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAllowedUser", reflect.TypeOf((*MockAuthService)(nil).UpdateAllowedUser), ctx, id, isAdmin)
}
