// Code generated by MockGen. DO NOT EDIT.
// Source: repository_port.go
//
// Generated by this command:
//
//	mockgen -source=repository_port.go -destination=../../../test/unit/doubles/shared_kernel/usecases/repository_port_mock.go -package=usecases -mock_names=UserRepository=MockUserRepository,TenantRepository=MockTenantRepository,TenantConfigurationRepository=MockTenantConfigurationRepository,PushTokenRepository=MockPushTokenRepository
//

// Package usecases is a generated GoMock package.
package usecases

import (
	context "context"
	reflect "reflect"
	domain "zensor-server/internal/shared_kernel/domain"
	usecases "zensor-server/internal/shared_kernel/usecases"

	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// FindByTenant mocks base method.
func (m *MockUserRepository) FindByTenant(ctx context.Context, tenantID domain.ID) ([]domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTenant", ctx, tenantID)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTenant indicates an expected call of FindByTenant.
func (mr *MockUserRepositoryMockRecorder) FindByTenant(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTenant", reflect.TypeOf((*MockUserRepository)(nil).FindByTenant), ctx, tenantID)
}

// GetByID mocks base method.
func (m *MockUserRepository) GetByID(arg0 context.Context, arg1 domain.ID) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryMockRecorder) GetByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepository)(nil).GetByID), arg0, arg1)
}

// Upsert mocks base method.
func (m *MockUserRepository) Upsert(arg0 context.Context, arg1 domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockUserRepositoryMockRecorder) Upsert(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockUserRepository)(nil).Upsert), arg0, arg1)
}

// MockTenantRepository is a mock of TenantRepository interface.
type MockTenantRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTenantRepositoryMockRecorder
	isgomock struct{}
}

// MockTenantRepositoryMockRecorder is the mock recorder for MockTenantRepository.
type MockTenantRepositoryMockRecorder struct {
	mock *MockTenantRepository
}

// NewMockTenantRepository creates a new mock instance.
func NewMockTenantRepository(ctrl *gomock.Controller) *MockTenantRepository {
	mock := &MockTenantRepository{ctrl: ctrl}
	mock.recorder = &MockTenantRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantRepository) EXPECT() *MockTenantRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTenantRepository) Create(ctx context.Context, tenant domain.Tenant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tenant)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTenantRepositoryMockRecorder) Create(ctx, tenant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTenantRepository)(nil).Create), ctx, tenant)
}

// FindAll mocks base method.
func (m *MockTenantRepository) FindAll(ctx context.Context, includeDeleted bool, pagination usecases.Pagination) ([]domain.Tenant, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, includeDeleted, pagination)
	ret0, _ := ret[0].([]domain.Tenant)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAll indicates an expected call of FindAll.
func (mr *MockTenantRepositoryMockRecorder) FindAll(ctx, includeDeleted, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockTenantRepository)(nil).FindAll), ctx, includeDeleted, pagination)
}

// GetByID mocks base method.
func (m *MockTenantRepository) GetByID(ctx context.Context, id domain.ID) (domain.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTenantRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTenantRepository)(nil).GetByID), ctx, id)
}

// GetByName mocks base method.
func (m *MockTenantRepository) GetByName(ctx context.Context, name string) (domain.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(domain.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockTenantRepositoryMockRecorder) GetByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockTenantRepository)(nil).GetByName), ctx, name)
}

// Update mocks base method.
func (m *MockTenantRepository) Update(ctx context.Context, tenant domain.Tenant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, tenant)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTenantRepositoryMockRecorder) Update(ctx, tenant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTenantRepository)(nil).Update), ctx, tenant)
}

// MockTenantConfigurationRepository is a mock of TenantConfigurationRepository interface.
type MockTenantConfigurationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTenantConfigurationRepositoryMockRecorder
	isgomock struct{}
}

// MockTenantConfigurationRepositoryMockRecorder is the mock recorder for MockTenantConfigurationRepository.
type MockTenantConfigurationRepositoryMockRecorder struct {
	mock *MockTenantConfigurationRepository
}

// NewMockTenantConfigurationRepository creates a new mock instance.
func NewMockTenantConfigurationRepository(ctrl *gomock.Controller) *MockTenantConfigurationRepository {
	mock := &MockTenantConfigurationRepository{ctrl: ctrl}
	mock.recorder = &MockTenantConfigurationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantConfigurationRepository) EXPECT() *MockTenantConfigurationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTenantConfigurationRepository) Create(arg0 context.Context, arg1 domain.TenantConfiguration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTenantConfigurationRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTenantConfigurationRepository)(nil).Create), arg0, arg1)
}

// GetByTenantID mocks base method.
func (m *MockTenantConfigurationRepository) GetByTenantID(arg0 context.Context, arg1 domain.ID) (domain.TenantConfiguration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTenantID", arg0, arg1)
	ret0, _ := ret[0].(domain.TenantConfiguration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTenantID indicates an expected call of GetByTenantID.
func (mr *MockTenantConfigurationRepositoryMockRecorder) GetByTenantID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTenantID", reflect.TypeOf((*MockTenantConfigurationRepository)(nil).GetByTenantID), arg0, arg1)
}

// Update mocks base method.
func (m *MockTenantConfigurationRepository) Update(arg0 context.Context, arg1 domain.TenantConfiguration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTenantConfigurationRepositoryMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTenantConfigurationRepository)(nil).Update), arg0, arg1)
}

// MockPushTokenRepository is a mock of PushTokenRepository interface.
type MockPushTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPushTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockPushTokenRepositoryMockRecorder is the mock recorder for MockPushTokenRepository.
type MockPushTokenRepositoryMockRecorder struct {
	mock *MockPushTokenRepository
}

// NewMockPushTokenRepository creates a new mock instance.
func NewMockPushTokenRepository(ctrl *gomock.Controller) *MockPushTokenRepository {
	mock := &MockPushTokenRepository{ctrl: ctrl}
	mock.recorder = &MockPushTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPushTokenRepository) EXPECT() *MockPushTokenRepositoryMockRecorder {
	return m.recorder
}

// DeleteByToken mocks base method.
func (m *MockPushTokenRepository) DeleteByToken(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByToken indicates an expected call of DeleteByToken.
func (mr *MockPushTokenRepositoryMockRecorder) DeleteByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByToken", reflect.TypeOf((*MockPushTokenRepository)(nil).DeleteByToken), ctx, token)
}

// GetByUserID mocks base method.
func (m *MockPushTokenRepository) GetByUserID(ctx context.Context, userID domain.ID) (domain.PushToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].(domain.PushToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockPushTokenRepositoryMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockPushTokenRepository)(nil).GetByUserID), ctx, userID)
}

// Upsert mocks base method.
func (m *MockPushTokenRepository) Upsert(ctx context.Context, pushToken domain.PushToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, pushToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockPushTokenRepositoryMockRecorder) Upsert(ctx, pushToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockPushTokenRepository)(nil).Upsert), ctx, pushToken)
}
