// Code generated by MockGen. DO NOT EDIT.
// Source: mailersend_client.go
//
// Generated by this command:
//
//	mockgen -source=mailersend_client.go -destination=../../../test/unit/doubles/infra/notification/mailersend_client_mock.go -package=notification -mock_names=MailerSendClient=MockMailerSendClient
//

// Package notification is a generated GoMock package.
package notification
