name: Test Application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  ENV: local

jobs:
  test-unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.20"

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Run unit tests
        run: just unit internal

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverprofile.out
          retention-days: 30

  test-functional-tenant:
    name: Functional Tests - Tenant
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        test_pattern: ["@tenant", "@task"]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.20"

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Build application
        run: just build

      - name: Run functional tests
        run: just functional "${{ matrix.test_pattern }}"
        env:
          ENV: local

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            api.log
            *.log
          retention-days: 7 